-- Create Brands table
create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text,
  image text,
  description text,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updatedAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add unique constraint on name
alter table public.brands add constraint brands_name_key unique (name);

-- Add brandId foreign key to products table if it doesn't exist
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'brandId') then
    alter table public.products add column "brandId" bigint references public.brands(id);
  end if;
end $$;
